"""Quadruplet construction: structured stimulus + 3 controls sharing quadruplet_id.

Roles:
  structured       -- the source stimulus, generated by one of five families.
  shuffled         -- a random permutation of the structured stimulus
                      (preserves multiset of tokens, destroys order).
  markov_pastiche  -- order-2 Markov chain trained on the structured stimulus
                      and resampled (preserves bigram statistics; long-range
                      structure flattened).
  random_match     -- iid sample from the empirical unigram of the structured
                      stimulus (preserves marginals only).
"""

from __future__ import annotations

from collections import Counter

import numpy as np

ROLES = ("structured", "shuffled", "markov_pastiche", "random_match")


def shuffle_control(rng: np.random.Generator, seq: np.ndarray) -> np.ndarray:
    out = seq.copy()
    rng.shuffle(out)
    return out


def random_match_control(rng: np.random.Generator, seq: np.ndarray, vocab: int) -> np.ndarray:
    """Sample iid from the empirical unigram of `seq`."""
    counts = np.zeros(vocab, dtype=np.float64)
    for token, c in Counter(seq.tolist()).items():
        counts[int(token)] = c
    probs = counts / counts.sum()
    return rng.choice(vocab, size=seq.shape[0], p=probs).astype(np.int64)


def markov_pastiche_control(
    rng: np.random.Generator, seq: np.ndarray, vocab: int, order: int = 1
) -> np.ndarray:
    """Train an order-`order` Markov chain on `seq` and resample length(seq).

    Default order=1 (bigram pastiche). At order=1 there are only `vocab`
    contexts, so 128 observations give ~8 samples per context — enough for
    the empirical distribution to dominate Laplace smoothing.

    Smoothing is α=1e-3, just large enough to keep the conditional defined
    when a context happens to never appear in the data; the data itself
    dominates wherever it is present.
    """
    n = seq.shape[0]
    alpha = 1e-3
    counts = np.full((vocab,) * order + (vocab,), alpha, dtype=np.float64)
    seq_list = seq.tolist()
    for t in range(order, n):
        ctx = tuple(seq_list[t - order : t])
        counts[ctx + (seq_list[t],)] += 1.0
    probs = counts / counts.sum(axis=-1, keepdims=True)

    out = np.empty(n, dtype=np.int64)
    out[:order] = seq[:order]  # share the prefix so first-bigram surprisal matches
    for t in range(order, n):
        ctx = tuple(int(out[t - order + j]) for j in range(order))
        p = probs[ctx]
        out[t] = int(rng.choice(vocab, p=p))
    return out


def build_quadruplet(
    rng: np.random.Generator, structured: np.ndarray, vocab: int
) -> dict[str, np.ndarray]:
    """Return {role: sequence} for all four siblings sharing a quadruplet_id."""
    return {
        "structured": structured.copy(),
        "shuffled": shuffle_control(rng, structured),
        "markov_pastiche": markov_pastiche_control(rng, structured, vocab),
        "random_match": random_match_control(rng, structured, vocab),
    }
